import { defineConfig } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// eslint-config-next 16 ships native flat configs, so the old FlatCompat
// bridge (@eslint/eslintrc) is no longer needed.
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      // Generated by next-pwa at build time.
      "public/sw.js",
      "public/workbox-*.js",
      // Plain Node CLI script (CommonJS require is fine there).
      "scripts/**",
    ],
  },
  {
    // eslint-config-next 16 enables the React Compiler lint rules. They flag
    // long-standing patterns in this codebase (setState inside effects to
    // hydrate from localStorage, etc.) that predate the upgrade. Reported as
    // warnings so `npm run lint` stays green while they are cleaned up.
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/static-components": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/immutability": "warn",
    },
  },
]);

export default eslintConfig;
